version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 65M
        reservations:
          cpus: '0.015'
          memory: 30M

  homepage:
    image: oelrm/doxgxxn.github.io
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST= fly.io.local
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.017'
          memory: 15M
        reservations:
          cpus: '0.01'
          memory: 6M






































# version: '2'

# services:
#   nginx-proxy:
#     image: nginxproxy/nginx-proxy
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#     # depends_on:
#     #   - odg
#     #   - shw
#     #   - tjk

#     deploy:
#       resources:
#         limits:
#           cpus: '0.20'
#           memory: 77M
#         reservations:
#           cpus: '0.01'
#           memory: 30M

#   odg:
#     image: oelrm/doxgxxn.github.io
#     expose:
#       - "80"
#     environment:
#       - VIRTUAL_HOST=odg.example
#       - VIRTUAL_PORT=80
#     # deploy:
#     #   mode: replicated
#     #   replicas: 2 # https://docs.docker.com/compose/compose-file/deploy/#replicas
#     #   resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
#     #     limits:
#     #       cpus: '0.05'
#     #       memory: 10M
#     #     reservations:
#     #       cpus: '0.01'
#     #       memory: 6M

#   shw:
#     image: seohyeongwon/8trider.github.io:1.1.0
#     expose:
#       - "800"
#     environment:
#       - VIRTUAL_HOST=shw.naver.com
#       - VIRTUAL_PORT=800

#   tjk:
#     image: tjkpolisher/tjkpolisher.github.io:latest
#     expose:
#       - "80"
#     environment:
#       - VIRTUAL_HOST=tjk.google.com
#       - VIRTUAL_PORT=80